config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.separate_comma(number) # 금액의 경우 단위수 별로 , 로 나눠줌 (오픈소스참조)
    if number.to_i > 0
      number = number.to_f.floor # 숫자 내림
      whole, decimal = number.to_s.split(".")
      whole_with_commas = whole&.chars.to_a.reverse.each_slice(3).map(&:join).join(",").reverse
      [whole_with_commas, decimal].compact.join(".")
    elsif number.to_i < 0
      number = number.to_f.abs.floor
      whole, decimal = number.to_s.split(".")
      whole_with_commas = whole&.chars.to_a.reverse.each_slice(3).map(&:join).join(",").reverse
      "-" + [whole_with_commas, decimal].compact.join(".")
    else
      return "-"
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, foreign_key: 'postId'
  belongs_to :user, foreign_key: 'userId'

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, foreign_key: 'refId'
  belongs_to :user, foreign_key: 'userId'

end

app/models/post.rb
class Post < ApplicationRecord
  enum isDeleted: [:no, :yes]
  has_one :posts_question, foreign_key: 'postId'
  has_one :posts_plaza, foreign_key: 'postId'
  has_one :posts_answer, foreign_key: 'postId'
  has_one :posts_review, foreign_key: 'postId'
  has_many :likes, foreign_key: 'refId'
  has_many :comments, foreign_key: 'refId'
  belongs_to :user, foreign_key: 'userId'

  def self.find_recent_week
    postlist = Post.ransack(createdDate_gteq: (Date.today - 6), createdDate_lteq: Date.today).result().group_by_day(:createdDate).count
    (0..6).each do |i|
      if !postlist.keys.include?(Date.today - i) #해당 날짜 데이터가 없으면 0으로 추가
        postlist.store(Date.today - i, 0)
      end
      postlist[(Date.today-i).strftime("%Y-%m-%d")] = postlist.delete (Date.today - i)
    end
    return postlist
  end

end

app/models/posts_answer.rb
class PostsAnswer < ApplicationRecord
  belongs_to :post, foreign_key: 'postId'
  belongs_to :posts_question, foreign_key: 'postId_Q'

  scope :select_answer, ->{where(isSelected: 1)}
  scope :unselect_answer, ->{where(isSelected: nil)}

end

app/models/posts_plaza.rb
class PostsPlaza < ApplicationRecord
  belongs_to :post, foreign_key: 'postId'

end

app/models/posts_question.rb
class PostsQuestion < ApplicationRecord
  belongs_to :post, foreign_key: 'postId'
  has_many :posts_answers, foreign_key: 'postId_Q'

  scope :select_answer, ->{joins(:posts_answers).where("posts_answers.isSelected = ?", 1)}
  scope :unselect_answer, ->{where.not(id: PostsQuestion.joins(:posts_answers).where("posts_answers.isSelected = ?", 1).ids)}

  def find_answer_list
    PostsAnswer.where(postId_Q: self.id)
  end

  def count_answer_list
    self.find_answer_list.count
  end

  def check_selected
    self.find_answer_list.where(isSelected: 1).present?
  end

  def self.filter_by_answer(isSelected)
    joins(:posts_answers).where("posts_answers.isSelected = ?", isSelected)
  end

  #  Add your custom method as ransack
  def self.ransackable_scopes(_auth_object = nil)
    [:filter_by_answer]
  end

end

app/models/posts_review.rb
class PostsReview < ApplicationRecord
  belongs_to :post, foreign_key: 'postId'

end

app/models/static_major.rb
class StaticMajor < ApplicationRecord



end

app/models/static_posts_plazas_type.rb
class StaticPostsPlazasType < ApplicationRecord



end

app/models/static_posts_questions_type.rb
class StaticPostsQuestionsType < ApplicationRecord



end

app/models/static_posts_reviews_type.rb
class StaticPostsReviewsType < ApplicationRecord



end

app/models/static_ref_type.rb
class StaticRefType < ApplicationRecord



end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'userId'
  has_many :comments, foreign_key: 'userId'

  def self.find_recent_week
    userlist = User.ransack(createdDate_gteq: (Date.today - 6), createdDate_lteq: Date.today).result().group_by_day(:createdDate).count
    (0..6).each do |i|
      if !userlist.keys.include?(Date.today - i) #해당 날짜 데이터가 없으면 0으로 추가
        userlist.store(Date.today - i, 0)
      end
      userlist[(Date.today-i).strftime("%Y-%m-%d")] = userlist.delete (Date.today - i)
    end
    return userlist
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/_index.html.erb
<div class="info_card_list">
  <div class="info_card user_info">
    <div class="icon">
      <i class="fa fa-user-circle" aria-hidden="true"></i>
    </div>
    <div class="info_text">
      <h3 class="info_title">총 사용자 수</h3>
      <p class="info_content"><%= User.separate_comma(@users) %></p>
    </div>
  </div>
  <div class="info_card post_info">
    <div class="icon">
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
    </div>
    <div class="info_text">
      <h3 class="info_title">총 게시글 수</h3>
      <p class="info_content"><%= @posts %></p>
    </div>
  </div>
  <div class="info_card comment_info">
    <div class="icon">
      <i class="fa fa-comments" aria-hidden="true"></i>
    </div>
    <div class="info_text">
      <h3 class="info_title">총 댓글 수</h3>
      <p class="info_content"><%= @comments %></p>
    </div>
  </div>
  <div class="info_card question_info">
    <div class="icon">
      <i class="fa fa-check-square-o" aria-hidden="true"></i>
    </div>
    <div class="info_text">
      <h3 class="info_title">질문 해결률</h3>
      <p class="info_content"><%= @question_accuracy %> %</p>
    </div>
  </div>
</div>



<div class="flex">
  <div style="display:inline-block; float:left; width:48%;" class="mx-2" >
    <div class="panel">
      <div class="panel_contents graph_panel_contents">
        <div class="graph_title">
          <h1>최근 1주일 신규 사용자</h1>
        </div>
        <div class="graph_container">
          <%= line_chart @recent_users.sort, colors: ["#f88379"], discrete: true %>
        </div>
        <div class="graph_content">
          <h1 class="graph_content"><%= @recent_users.values.sum %> 명</h1>
        </div>
      </div>
    </div>
  </div>
  <div style="width:48%; display:inline-block;" class="mx-2">
    <div class="panel">
      <div class="panel_contents graph_panel_contents">
        <div class="graph_title">
          <h1>최근 1주일 신규 게시글</h1>
        </div>
        <div class="graph_container">
          <%= line_chart @recent_posts.sort, colors: ["#4169e1"], discrete: true %>
        </div>
        <div class="graph_content">
          <h1 class="graph_content"><%= @recent_posts.values.sum %> 개</h1>
        </div>
      </div>
    </div>
  </div>

  <div style="width:30%; height:20%; display:inline-block;">
      <div id="panel">
        <div class="index_content">
          <div class="index_as_table panel" style="text-align:center;">
            <table border="0" cellspacing="0" cellpadding="0" id="index_table_withdraws" class="index_table index" paginator="true">
              <tbody>
                <tr class="row">
                  <th colspan="2"></th>
                </tr>
                <tr class="row">
                  <th class="bg-blue white center" colspan="2">최근 1주일 게시글 추이</th>
                </tr>
                <tr class="row">
                  <th class="center">전체</th>
                  <th class="center"><%= @weekly_posts %></th>
                </tr>
                <tr class="row">
                  <th class="center">자유게시글</th>
                  <th class="center"><%= @free_posts %></th>
                </tr>
                <tr class="row">
                  <th class="center">질문게시글</th>
                  <th class="center"><%= @question_posts %></th>
                </tr>
                <tr class="row">
                  <th class="center">답변게시글</th>
                  <th class="center"><%= @answer_posts %></th>
                </tr>
                <tr class="row">
                  <th class="center">수기게시판</th>
                  <th class="center"><%= @review_posts %></th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>

  <div style="width:60%; height:20%; display:inline-block; float:right;">
    <div id="panel">
      <div class="index_content">
        <div class="index_as_table panel" style="text-align:center;">
          <table border="0" cellspacing="0" cellpadding="0" id="index_table_withdraws" class="index_table index" paginator="true">
            <tbody>
              <tr class="row">
                <th class="bg-blue white center" colspan="4">최근 1주일 베스트 인기 게시글</th>
              </tr>
              <tr class="row">
                <th class="center">추천수</th>
                <th class="center">게시글</th>
                <th class="center">작성자</th>
                <th class="center">지갑주소</th>
              </tr>
              <% @hot_posts.each do |hot_post| %>
                <tr class="row">
                  <th class="center"><%= hot_post.likes.count %></th>
                  <th class="center"><%= link_to hot_post.title, admin_posts_review_path(hot_post.posts_review&.id) %></th>
                  <th class="center"><%= link_to hot_post.user.name, admin_user_path(hot_post.user.id) %></th>
                  <th class="center"><%= hot_post.user.walletAddress%></th>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">
  $('#main_content').css({"background":"none","box-shadow":"none"}) // 불필요한 흰색 박스 제거 (active admin default css)
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doajou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>